// Reference library of proven CNC plasma niches. This is starter content drawn
// from common plasma-industry markets — Charles can edit, reorder, or replace
// any of these in one place.
export const NICHES = [
  {
    id: 'ranch-farm',
    emoji: '🤠',
    title: 'Ranch & Farm Signs',
    tagline: 'Entrance signs, brands, and gate markers for ranchers and farmers.',
    products: ['Ranch entrance signs', 'Cattle brand cutouts', 'Gate & fence toppers', 'Barn quilt panels'],
    buyers: 'Ranch and farm owners, rural landowners, 4-H and FFA families.',
    why: 'High perceived value and deeply personal — a custom brand sign is a legacy piece people happily pay premium for. Easy to upsell into matching pieces.',
  },
  {
    id: 'jeep-offroad',
    emoji: '🚙',
    title: 'Jeep & Off-Road',
    tagline: 'Trail badges, grille inserts, and accessories for the off-road crowd.',
    products: ['Custom grille inserts', 'Trail/light covers', 'Hood decals', 'Spare tire mounts'],
    buyers: 'Jeep clubs, overlanders, truck and UTV owners who mod their rigs.',
    why: 'A passionate, brand-loyal community that loves personalizing their vehicles and buys repeatedly. Strong social-media sharing built in.',
  },
  {
    id: 'address-markers',
    emoji: '🏡',
    title: 'Address & Property Markers',
    tagline: 'Custom house numbers, driveway signs, and acreage markers.',
    products: ['Address number signs', 'Driveway markers', 'Reflective property signs', 'Last-name plaques'],
    buyers: 'New homeowners, rural property owners, realtors and builders.',
    why: 'Practical purchase with an emotional hook — everyone wants their home to look sharp. Repeatable design system makes production fast.',
  },
  {
    id: 'sports-team',
    emoji: '🏈',
    title: 'Sports & Team Decor',
    tagline: 'Team logos, mascots, and fan wall art for local pride.',
    products: ['Team logo wall art', 'Mascot cutouts', 'Jersey-number signs', 'Stadium-style decor'],
    buyers: 'Sports parents, booster clubs, schools, sports bars, superfans.',
    why: 'Seasonal demand spikes and strong group/bulk orders from teams and boosters. Licensing-safe when you stick to local schools and original designs.',
  },
  {
    id: 'outdoor-hunting',
    emoji: '🦌',
    title: 'Hunting, Fishing & Outdoors',
    tagline: 'Wildlife scenes and outdoorsman decor for cabins and man caves.',
    products: ['Wildlife wall scenes', 'Cabin signs', 'Gun-rack accents', 'Fish & deer silhouettes'],
    buyers: 'Hunters, anglers, cabin owners, outdoor enthusiasts.',
    why: 'Buyers identify hard with the lifestyle and decorate around it. Great for layered, multi-color powder-coat pieces that command higher prices.',
  },
  {
    id: 'faith-based',
    emoji: '✝️',
    title: 'Faith-Based Decor',
    tagline: 'Scripture art, crosses, and church signage.',
    products: ['Scripture wall art', 'Decorative crosses', 'Church directional signs', 'Prayer/blessing pieces'],
    buyers: 'Churches, faith-driven homeowners, religious gift buyers.',
    why: 'Deeply meaningful purchases with strong gift and repeat potential. Loyal word-of-mouth community that shares within congregations.',
  },
  {
    id: 'memorial',
    emoji: '🕊️',
    title: 'Memorial & Pet Tributes',
    tagline: 'Personalized keepsakes honoring loved ones and pets.',
    products: ['Memorial garden stakes', 'Pet portrait cutouts', 'Remembrance plaques', 'Photo silhouette art'],
    buyers: 'Grieving families, pet owners, memorial gift givers.',
    why: 'Among the highest emotional value per piece — price sensitivity is low and reviews are heartfelt. Steady, recession-resistant demand.',
  },
  {
    id: 'business-signage',
    emoji: '🏢',
    title: 'Business & Storefront Signage',
    tagline: 'Logos, hours, and branded decor for local businesses.',
    products: ['Logo signs', 'Open/hours signs', 'Branded wall art', 'Directional & menu signs'],
    buyers: 'Local shops, restaurants, breweries, salons, real estate offices.',
    why: 'Higher ticket B2B orders and repeat/referral business. One happy storefront becomes a walking advertisement for your work.',
  },
  {
    id: 'home-monogram',
    emoji: '🔠',
    title: 'Home Decor & Monograms',
    tagline: 'Family names, monograms, and statement wall art.',
    products: ['Family-name signs', 'Split-letter monograms', 'Established-date signs', 'Kitchen & patio art'],
    buyers: 'Homeowners, newlyweds, housewarming gift buyers.',
    why: 'Broad mass-market appeal and a natural gift item. Personalization drives premium pricing and easy bulk/wedding-season runs.',
  },
  {
    id: 'first-responder',
    emoji: '🚒',
    title: 'First Responder & Military',
    tagline: 'Tribute pieces for fire, police, EMS, and veterans.',
    products: ['Thin-line flag art', 'Department logo signs', 'Veteran tribute pieces', 'Station/unit decor'],
    buyers: 'First responders, veterans, their families, and supporters.',
    why: 'A proud, tight-knit community that buys to show identity and gratitude. Strong fundraiser and group-order opportunities.',
  },
  {
    id: 'holiday-seasonal',
    emoji: '🎄',
    title: 'Holiday & Seasonal Decor',
    tagline: 'Christmas, Halloween, and fall pieces that sell on a yearly clock.',
    products: ['Christmas tree & ornament cutouts', 'Halloween yard silhouettes', 'Fall/harvest signs', 'Seasonal porch decor'],
    buyers: 'Homeowners, gift buyers, holiday-market and craft-fair shoppers.',
    why: 'Predictable demand spikes you can plan production around, and the same customers come back every season. Great for batch runs and limited drops.',
  },
  {
    id: 'bbq-grilling',
    emoji: '🔥',
    title: 'BBQ, Grilling & Smoker',
    tagline: 'Custom grill gear and branding for the backyard cook.',
    products: ['Custom grill grates', 'Smoker plates & vents', 'Steak/meat branding irons', 'Fire pits'],
    buyers: 'Backyard grillers, competition BBQ teams, tailgaters, gift buyers.',
    why: 'Functional and gift appeal in one, with a passionate hobby crowd that upgrades constantly. Higher-ticket fabrication beyond flat signage.',
  },
  {
    id: 'wedding-events',
    emoji: '💍',
    title: 'Wedding & Events',
    tagline: 'Backdrops, signage, and keepsakes for weddings and parties.',
    products: ['Backdrop monograms', 'Welcome & seating signs', 'Cake toppers', 'Table numbers'],
    buyers: 'Brides and grooms, event planners, venues, party hosts.',
    why: 'High-margin, emotional purchases with natural bulk orders and a strong seasonal calendar. Venues and planners become repeat referral sources.',
  },
  {
    id: 'lake-nautical',
    emoji: '⚓',
    title: 'Lake, Nautical & Coastal',
    tagline: 'Lake-house and coastal decor for the water-life crowd.',
    products: ['Lake-house signs', 'Fish & anchor silhouettes', 'Dock & boat-slip markers', 'Compass & map art'],
    buyers: 'Lake and beach homeowners, boaters, vacation-rental owners.',
    why: 'Lifestyle buyers who decorate their whole space around the theme, so one sale opens the door to matching pieces. Strong vacation-rental demand.',
  },
  {
    id: 'trades-industry',
    emoji: '🛠️',
    title: 'Trades & Industry Pride',
    tagline: 'Identity decor and company gifts for working trades.',
    products: ['Trade-logo wall art (welding, oilfield, electrical)', 'Company-branded signs', 'Hard-hat & rig decor', 'Crew gift pieces'],
    buyers: 'Tradespeople, contractors, oilfield and construction companies.',
    why: 'Blends personal identity with B2B orders — companies buy in bulk for crews and clients, and trade pride drives steady repeat purchases.',
  },
  {
    id: 'garden-outdoor',
    emoji: '🌿',
    title: 'Garden & Outdoor Living',
    tagline: 'Functional metalwork for yards, patios, and gardens.',
    products: ['Trellises & plant stands', 'Garden stakes & markers', 'Hose holders', 'Decorative panels & screens'],
    buyers: 'Gardeners, homeowners, landscapers, patio decorators.',
    why: 'Practical pieces with broad mass-market appeal that take you beyond signage into higher-value fabrication. Pairs well with spring/summer demand.',
  },
  {
    id: 'auto-moto-garage',
    emoji: '🏁',
    title: 'Auto, Moto & Garage',
    tagline: 'Gearhead decor and emblems for car and bike lovers.',
    products: ['Custom emblems & badges', 'Garage & shop signs', 'Engine/piston wall art', 'Motorcycle decor'],
    buyers: 'Car and motorcycle enthusiasts, restorers, garage and shop owners.',
    why: 'A broad, brand-loyal hobby community that personalizes their space and rigs and buys repeatedly. Wider reach than a single make like Jeep.',
  },
];
